### ISSUE TITLE
"Invalid file provided" errors – manual upload of same file is working though

### ISSUE THREAD

**Issue by Jeehut** [dag-io/appetize-deploy-step#4]
I have just tried to integrate Appetize with our Android and iOS apps. While Android was working without any issues, I tried fixing the issues on iOS with the tips from this thread. But it's not working, neither on the Bitrise CI nor when I run it locally on my Mac (that's what the support asked me to do).

Here's the CI output:
```
[Exception]
  Invalid file provided "/var/folders/2l/3tqwt0g91x18hql0jwsz0y280000gn/T/deploy149227386/MyApp.app.zip"
```

Funny thing is, when I upload the exact same `.app.zip` file manually through the Appetize web interface, it's all working just fine. Also note that the error message is coming right away, so I doubt it's trying any uploading.

Here are my two steps from the workflow:

```yaml
    - script:
        title: Prepare .app.zip for Appetize
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex

            # generate the `.app` into a specified "derived data" dir
            xcodebuild build -project ./$BITRISE_PROJECT_PATH -scheme $BITRISE_SCHEME -configuration Debug -sdk iphonesimulator11.2 -derivedDataPath ./ddata

            # change dir into the derived data dir -> Build -> Products -> Debug-iphonesimulator
            # the .app is generated into this with the above configs (-configuration Debug -sdk iphonesimulatorX.Y -derivedDataPath ./ddata)
            cd ./ddata/Build/Products/Debug-iphonesimulator/

            # now zip it up!
            zip -r $BITRISE_SCHEME.app.zip $BITRISE_SCHEME.app

            # finally, move it into e.g. the bitrise deploy dir
            mv $BITRISE_SCHEME.app.zip "$BITRISE_DEPLOY_DIR/$BITRISE_SCHEME.app.zip"
    - appetize-deploy:
        run_if: "true"
        inputs:
        - appetize_token: tok_abcdefghijklmnopqrstuvw1234567890
        - app_path: $BITRISE_DEPLOY_DIR/$BITRISE_SCHEME.app.zip
```

Do you have any ideas why it's failing?
